name: Hello Testing

on:
  push:
    branches:
      - master
      - production

jobs:
  hello_job:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World
        run: echo "Hello World"

      - name: Print Current Date
        run: date  