name: "Multiple Event Workflows"

on:
  push:
    branches:
      - master
      - test

  pull_request:
    branches:
      - master

    types:
      - closed
      - opened

  workflow_dispatch:

jobs:
  on-push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Running on Master/Test Push
        run: echo "Running on Master/Test Push"

  on-pull-request:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Running on Pull Request
        run: echo "Running on Pull Request"

  on-pull-request-closed:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest

    steps:
      - name: Pull Request Closed
        run: echo "Pull Request has been closed."   
        
  on-pull-request-opened:
    if: github.event.action == 'opened'
    runs-on: ubuntu-latest

    steps:
      - name: Pull Request Opened
        run: echo "Pull Request has been opened."       

  on-workflow-dispatch:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Running on Workflow Dispatch
        run: echo "Running on Workflow Dispatch"